# Generated by Django 5.1.1 on 2024-10-08 10:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchaser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_courses', models.ManyToManyField(blank=True, related_name='purchasers', to='payment.tutorials')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchasers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
